### PR TITLE
macOS Sierra compatibility

### PR DESCRIPTION
**Pull request by jasonfma**
I found the fix in the fastlane repo. Issue and fix linked below. This should solve issue #9 

https://github.com/fastlane/fastlane/issues/6387
https://github.com/fastlane/fastlane/pull/6388

 Additionally, I needed to change the `Certificate and profile installer` to use `$HOME/Library/Keychains/login.keychain-db` as the keychain path.

### CODE REVIEW

**Comment by trapacska** [comment]
Thank you for the PR! 🚀 It will be released soon, however this step will be deprecated. To do the same with supported functionality please use [export-xcarchive](https://github.com/bitrise-steplib/steps-export-xcarchive) step instead. 🎉

**Comment by jasonfma** [comment]
@trapacska the reason why I want to use this step is because I want to generate an `.ipa` but modify the internal configuration file so (I can make it point to different environments), and then resign them accordingly - without having to rebuild the binary for each environment.

e.g.
1) Export development `.ipa` with manual xcode 8 signing
2) copy to `.staging.ipa` and modify internal configuration
3) resign the modified `.staging.ipa`

Will I still be able do this with the `export-xarchive` step?

**Comment by trapacska** [comment]
The main question is that why would you need to modify internal configuration? 🙂 If because you need a development and app-store ipa, then it is not required to use this step.

You can do it with a basic workflow:
1) xcode-archive step -> generate development ipa (this step also has an xcarchive output)
2) export-xcarchive -> generate app-store ipa

🙂

**Comment by jasonfma** [comment]
I modify the internal configuration file so that it can point to different servers (e.g. development, staging, production). I still want all those to be development builds so that I can install them on device (without going through app store). I also want the production one to be app-store signed so I can submit it to itunes. So in this scenario, I would need 3 differently configured `.ipa`s with the production one being both development and app store signed.

Exporting different binaries or archives for each server configuration would be time consuming and also introduces more environment drift variability. Having a single binary that we test and deploy is important for us. Also, this effort would be doubled because we are cross platform and also have the same requirements for android.

I'm actually not confident this is the right approach either. So I'm open to suggestions. We're developing in react native.

**Comment by trapacska** [comment]
I understand. The main reason is we will deprecate this step is because there are other steps which contains more precise edge-case/error handling.

`export-xcarchive` step has an input `custom_export_options_plist_content`. There you can put your own configuration.

So if I would do the same what you need:
1) xcode-archive step -> generate development (this step is required anyway)
2) export-xcarchive -> generate staging
3) export-xcarchive -> generate app-store

This would be a very recommended way to do this, not because these newer steps are better in edge-case handling, but it is the official way to do it.

Export-xcarchive does not builds your code again-and-again, so it won't be a lot longer build time.

---

In case it is still better to use this step, you can do it two ways:
1) fork this repo, and use your fork in your bitrise.yml
instead of
`- resign-ipa`
you can use your fork like:
`- git::https://github.com/YOURUSER/steps-script.git@BRANCH-OR-TAG:`
(read more at [Steps - Bitrise DevCenter](http://devcenter.bitrise.io/bitrise-cli/steps/#special-step-sources)

2) call your own command from a script step.

Hope this helps 🙂

**Comment by jasonfma** [comment]
Ok. I'll take a look at what the archive gives us and see if that we can do it that way. Thanks for the help @trapacska :)

**Comment by viktorbenei** [comment]
Just a bit of help/note for @trapacska 's answer:

The "official" solution (in which I mean it only uses Xcode to do all the operations, no custom tool/scripting) is:

1. Use the Xcode Archive step to create a base, signed iOS app, as well as the `.xcarchive`. If you don't want to modify any files, or export other multiple IPAs with different signing then this is all you need.
1. If you have to change the __code__ in any way (including configs, embedded resources, etc.) you should do that any way you like (e.g. with a __Script__ step) and then use the Xcode Archive step (again). Xcode will make sure that everything's in order during the archive process; if that's successful the app will work. To speed up things make sure that the "Clean" build option (__Do a clean Xcode build before the archive?__ / `is_clean_build`) of Xcode Archive is set to `no`. Xcode in general is quite good in minimizing subsequent build times, so your second Xcode Archive step in the same build will be much faster.
1. If you don't want to modify the code, just simply sign the app with different signing files, then you should use an Xcode Archive step and then __Export iOS and tvOS Xcode archive__ or __Export macOS Xcode archive__. Doing an export from an archive (using Xcode, as the steps don't have any magic, it's all just Xcode) does not and can't change the code, and is the official solution if you want to make sure that you have the same app (IPA / built code) just with different code signings (e.g. one development, and one App Store IPA).

If you have any questions, just let us know! ;)

**Pull request merged**
